name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # 每天 UTC 时间 00:00 运行一次
  workflow_dispatch: # 允许手动触发

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create output directory
        run: mkdir -p output  # 确保 output 目录存在

      - name: Generate contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            output/github-contribution-grid-snake.svg
            output/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: snake
          path: output

      - name: Commit and push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add output
          git commit -m "Update contribution snake" || echo "No changes to commit"
          git push || echo "No changes to push"
